2024-03-07 09:46:48.089 [info] Test server listening.
2024-03-07 09:46:48.089 [info] > conda info --json
2024-03-07 09:46:48.089 [info] Python interpreter path: ~/template-python-code-envs/py38/bin/python
2024-03-07 09:46:48.089 [info] Found: /bin/python2 --> /bin/python2.7
2024-03-07 09:46:48.089 [info] Found: /bin/python2.7 --> /bin/python2.7
2024-03-07 09:46:48.089 [info] Found: /bin/python3 --> /usr/libexec/platform-python3.6
2024-03-07 09:46:48.090 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-03-07 09:46:48.103 [info] Found: /bin/python3.6 --> /usr/libexec/platform-python3.6
2024-03-07 09:46:48.107 [info] Found: /bin/python3.8 --> /bin/python3.8
2024-03-07 09:46:48.117 [info] Found: /bin/python3.9 --> /bin/python3.9
2024-03-07 09:46:48.162 [info] > ~/template-python-code-envs/py38/bin/python -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.171 [info] Found: /usr/bin/python2 --> /usr/bin/python2.7
2024-03-07 09:46:48.171 [info] Found: /usr/bin/python2.7 --> /usr/bin/python2.7
2024-03-07 09:46:48.188 [info] Found: /usr/bin/python3 --> /usr/libexec/platform-python3.6
2024-03-07 09:46:48.189 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-03-07 09:46:48.192 [info] Found: /usr/bin/python3.6 --> /usr/libexec/platform-python3.6
2024-03-07 09:46:48.192 [info] Found: /usr/bin/python3.8 --> /usr/bin/python3.8
2024-03-07 09:46:48.194 [info] Found: /usr/bin/python3.9 --> /usr/bin/python3.9
2024-03-07 09:46:48.202 [info] > ~/dataiku-python-code-envs/bin/python -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.214 [info] Found: /usr/local/bin/python3.10 --> /usr/local/bin/python3.10
2024-03-07 09:46:48.214 [info] Found: /usr/local/bin/python3.11 --> /usr/local/bin/python3.11
2024-03-07 09:46:48.215 [info] Found: /usr/local/bin/python3.7 --> /usr/local/bin/python3.7
2024-03-07 09:46:48.226 [info] > ~/dataiku-python-code-envs/py37-dss/bin/python -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.310 [info] > ~/dataiku-python-code-envs/pyenv/bin/python -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.321 [info] > /bin/python2 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.397 [info] > /bin/python3 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.399 [warning] [Error: Command failed: /bin/python2 -I /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:402:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Socket.<anonymous> (node:internal/child_process:458:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:301:12)] {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/bin/python2 -I /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py'
}
2024-03-07 09:46:48.399 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2024-03-07 09:46:48.411 [info] > /bin/python2 ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.910 [info] > . ~/template-python-code-envs/py38/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/printEnvVariables.py
2024-03-07 09:46:48.910 [info] shell: bash
2024-03-07 09:46:48.924 [info] > /bin/python3.11 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:48.998 [info] > /bin/python3.8 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.094 [info] > /bin/python3.9 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.330 [info] > /usr/bin/python2 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.334 [warning] [Error: Command failed: /usr/bin/python2 -I /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
Unknown option: -I
usage: /usr/bin/python2 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

	at ChildProcess.exithandler (node:child_process:402:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Socket.<anonymous> (node:internal/child_process:458:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:301:12)] {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/usr/bin/python2 -I /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py'
}
2024-03-07 09:46:49.334 [error] Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
2024-03-07 09:46:49.343 [info] > /usr/bin/python2 ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.378 [info] > /usr/bin/python3.11 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.395 [info] > /usr/bin/python3.8 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.421 [info] > /usr/bin/python3.9 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.483 [info] > /usr/local/bin/python3.10 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.511 [info] > /usr/local/bin/python3.11 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:49.595 [info] > /usr/local/bin/python3.7 -I ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/get_output_via_markers.py ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/interpreterInfo.py
2024-03-07 09:46:51.492 [info] Starting Jedi language server for workspace.
2024-03-07 09:48:56.107 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 09:48:56.542 [info] Send text to terminal: source /home/dataiku/template-python-code-envs/py38/bin/activate
2024-03-07 09:48:57.533 [info] Send text to terminal:  /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 42669 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py run --params FECHADATO:10000000,PIB_TRANSFER_PATH_PREFIX:/tmp/,BITACORA_ENV:des,USER:pepe 
2024-03-07 09:51:19.571 [info] > . ~/template-python-code-envs/py38/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/printEnvVariables.py
2024-03-07 09:51:19.571 [info] shell: bash
2024-03-07 09:51:19.612 [info] > ~/template-python-code-envs/py38/bin/python -c "import pytest"
2024-03-07 09:51:21.465 [info] > ~/template-python-code-envs/py38/bin/python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear project-lib-versioned
2024-03-07 09:51:21.465 [info] cwd: .
2024-03-07 09:51:25.986 [error] Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform linux -- Python 3.8.17, pytest-7.4.4, pluggy-0.13.1
rootdir: /home/dataiku/workspace
plugins: hypothesis-6.98.17


                          _           _     _                ____    _  __
                         | |         | |   (_)              |  _ \  | |/ /
   __ _   _ __     __ _  | |  _   _  | |_   _    ___   ___  | |_) | | ' / 
  / _` | | '_ \   / _` | | | | | | | | __| | |  / __| / __| |  _ <  |  <  
 | (_| | | | | | | (_| | | | | |_| | | |_  | | | (__  \__ \ | |_) | | . \ 
  \__,_| |_| |_|  \__,_| |_|  \__, |  \__| |_|  \___| |___/ |____/  |_|\_\
                               __/ |                                      
                              |___/                                       

                            ~Versión: 3.0.0 (ML)~                     

GIT commit id: NA.
collected 5 items / 1 error

<Package data_engineering>
  <Module test_data_engineering.py>
    <Function test_preparation_pipeline>
    <Function test_build_powerful_features_node>
<Package inference>
  <Module test_inference.py>
    <Function test_model_basic_validation>
    <Function test_bright_invariance_validation>
<Package integration>
  <Module test_integration.py>
    <Function test_default_pipeline>

==================================== ERRORS ====================================
_ ERROR collecting project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py _
ImportError while importing test module '/home/dataiku/workspace/project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py:9: in <module>
    import tensorflow.python.keras.models
E   ModuleNotFoundError: No module named 'tensorflow'
=============================== warnings summary ===============================
../template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if pa_version and LooseVersion(pa_version) < LooseVersion("2.0"):

../template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    __version_info__ = tuple(LooseVersion(__version__).version)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
===================== 5 tests collected, 1 error in 3.70s ======================

Traceback (most recent call last):
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/out/client/extension.js:2:241129)
	at Object.onceWrapper (node:events:628:26)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)]
2024-03-07 09:53:07.258 [info] Send text to terminal: source /home/dataiku/template-python-code-envs/py38/bin/activate
2024-03-07 10:05:52.177 [info] > . ~/template-python-code-envs/py38/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/printEnvVariables.py
2024-03-07 10:05:52.177 [info] shell: bash
2024-03-07 10:05:52.222 [info] > ~/template-python-code-envs/py38/bin/python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear project-lib-versioned
2024-03-07 10:05:52.222 [info] cwd: .
2024-03-07 10:05:56.714 [error] Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform linux -- Python 3.8.17, pytest-7.4.4, pluggy-0.13.1
rootdir: /home/dataiku/workspace
plugins: hypothesis-6.98.17


                          _           _     _                ____    _  __
                         | |         | |   (_)              |  _ \  | |/ /
   __ _   _ __     __ _  | |  _   _  | |_   _    ___   ___  | |_) | | ' / 
  / _` | | '_ \   / _` | | | | | | | | __| | |  / __| / __| |  _ <  |  <  
 | (_| | | | | | | (_| | | | | |_| | | |_  | | | (__  \__ \ | |_) | | . \ 
  \__,_| |_| |_|  \__,_| |_|  \__, |  \__| |_|  \___| |___/ |____/  |_|\_\
                               __/ |                                      
                              |___/                                       

                            ~Versión: 3.0.0 (ML)~                     

GIT commit id: NA.
collected 5 items / 1 error

<Package data_engineering>
  <Module test_data_engineering.py>
    <Function test_preparation_pipeline>
    <Function test_build_powerful_features_node>
<Package inference>
  <Module test_inference.py>
    <Function test_model_basic_validation>
    <Function test_bright_invariance_validation>
<Package integration>
  <Module test_integration.py>
    <Function test_default_pipeline>

==================================== ERRORS ====================================
_ ERROR collecting project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py _
ImportError while importing test module '/home/dataiku/workspace/project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py:9: in <module>
    import tensorflow.python.keras.models
E   ModuleNotFoundError: No module named 'tensorflow'
=============================== warnings summary ===============================
../template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if pa_version and LooseVersion(pa_version) < LooseVersion("2.0"):

../template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    __version_info__ = tuple(LooseVersion(__version__).version)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
===================== 5 tests collected, 1 error in 3.68s ======================

Traceback (most recent call last):
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/out/client/extension.js:2:241129)
	at Object.onceWrapper (node:events:628:26)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)]
2024-03-07 10:06:07.885 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:06:08.032 [info] Send text to terminal:  cd /home/dataiku/workspace ; /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 52387 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py 
2024-03-07 10:06:55.274 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:06:55.421 [info] Send text to terminal:  cd /home/dataiku/workspace ; /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 44331 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py 
2024-03-07 10:08:14.788 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:08:14.938 [info] Send text to terminal:  cd /home/dataiku/workspace ; /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 48701 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py 
2024-03-07 10:09:39.475 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:09:39.622 [info] Send text to terminal:  cd /home/dataiku/workspace/project-lib-versioned/python/test_project ; /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 58069 -- /home/dataiku/workspace/project-lib-versioned/python/test_project/src/test_project/main.py run --params FECHADATO:10000000,PIB_TRANSFER_PATH_PREFIX:/tmp/,BITACORA_ENV:des,USER:pepe 
2024-03-07 10:10:28.960 [info] > ~/template-python-code-envs/py38/bin/python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear project-lib-versioned
2024-03-07 10:10:28.960 [info] cwd: .
2024-03-07 10:10:33.490 [error] Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform linux -- Python 3.8.17, pytest-7.4.4, pluggy-0.13.1
rootdir: /home/dataiku/workspace
plugins: hypothesis-6.98.17


                          _           _     _                ____    _  __
                         | |         | |   (_)              |  _ \  | |/ /
   __ _   _ __     __ _  | |  _   _  | |_   _    ___   ___  | |_) | | ' / 
  / _` | | '_ \   / _` | | | | | | | | __| | |  / __| / __| |  _ <  |  <  
 | (_| | | | | | | (_| | | | | |_| | | |_  | | | (__  \__ \ | |_) | | . \ 
  \__,_| |_| |_|  \__,_| |_|  \__, |  \__| |_|  \___| |___/ |____/  |_|\_\
                               __/ |                                      
                              |___/                                       

                            ~Versión: 3.0.0 (ML)~                     

GIT commit id: NA.
collected 5 items / 1 error

<Package data_engineering>
  <Module test_data_engineering.py>
    <Function test_preparation_pipeline>
    <Function test_build_powerful_features_node>
<Package inference>
  <Module test_inference.py>
    <Function test_model_basic_validation>
    <Function test_bright_invariance_validation>
<Package integration>
  <Module test_integration.py>
    <Function test_default_pipeline>

==================================== ERRORS ====================================
_ ERROR collecting project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py _
ImportError while importing test module '/home/dataiku/workspace/project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py:9: in <module>
    import tensorflow.python.keras.models
E   ModuleNotFoundError: No module named 'tensorflow'
=============================== warnings summary ===============================
../template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if pa_version and LooseVersion(pa_version) < LooseVersion("2.0"):

../template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    __version_info__ = tuple(LooseVersion(__version__).version)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
===================== 5 tests collected, 1 error in 3.73s ======================

Traceback (most recent call last):
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/out/client/extension.js:2:241129)
	at Object.onceWrapper (node:events:628:26)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Socket.<anonymous> (node:internal/child_process:458:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:301:12)]
2024-03-07 10:10:38.324 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:10:38.475 [info] Send text to terminal:  cd /home/dataiku/workspace ; /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 46365 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py run --params FECHADATO:10000000,PIB_TRANSFER_PATH_PREFIX:/tmp/,BITACORA_ENV:des,USER:pepe 
2024-03-07 10:42:15.853 [info] DAP Server launched with command: /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter
2024-03-07 10:42:16.344 [info] Send text to terminal: source /home/dataiku/template-python-code-envs/py38/bin/activate
2024-03-07 10:42:17.359 [info] Send text to terminal:  /usr/bin/env /home/dataiku/template-python-code-envs/py38/bin/python /home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 43485 -- /home/dataiku/workspace/recipes/compute_analyticsbk_dataset.py run --params FECHADATO:10000000,PIB_TRANSFER_PATH_PREFIX:/tmp/,BITACORA_ENV:des,USER:pepe 
2024-03-07 11:11:16.803 [info] > . ~/template-python-code-envs/py38/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/printEnvVariables.py
2024-03-07 11:11:16.804 [info] shell: bash
2024-03-07 11:11:16.848 [info] > ~/template-python-code-envs/py38/bin/python ~/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear project-lib-versioned
2024-03-07 11:11:16.848 [info] cwd: .
2024-03-07 11:11:21.386 [error] Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform linux -- Python 3.8.17, pytest-7.4.4, pluggy-0.13.1
rootdir: /home/dataiku/workspace
plugins: hypothesis-6.98.17


                          _           _     _                ____    _  __
                         | |         | |   (_)              |  _ \  | |/ /
   __ _   _ __     __ _  | |  _   _  | |_   _    ___   ___  | |_) | | ' / 
  / _` | | '_ \   / _` | | | | | | | | __| | |  / __| / __| |  _ <  |  <  
 | (_| | | | | | | (_| | | | | |_| | | |_  | | | (__  \__ \ | |_) | | . \ 
  \__,_| |_| |_|  \__,_| |_|  \__, |  \__| |_|  \___| |___/ |____/  |_|\_\
                               __/ |                                      
                              |___/                                       

                            ~Versión: 3.0.0 (ML)~                     

GIT commit id: NA.
collected 5 items / 1 error

<Package data_engineering>
  <Module test_data_engineering.py>
    <Function test_preparation_pipeline>
    <Function test_build_powerful_features_node>
<Package inference>
  <Module test_inference.py>
    <Function test_model_basic_validation>
    <Function test_bright_invariance_validation>
<Package integration>
  <Module test_integration.py>
    <Function test_default_pipeline>

==================================== ERRORS ====================================
_ ERROR collecting project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py _
ImportError while importing test module '/home/dataiku/workspace/project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py:9: in <module>
    import tensorflow.python.keras.models
E   ModuleNotFoundError: No module named 'tensorflow'
=============================== warnings summary ===============================
../template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/fsspec/spec.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if pa_version and LooseVersion(pa_version) < LooseVersion("2.0"):

../template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24
  /home/dataiku/template-python-code-envs/py38/lib/python3.8/site-packages/great_expectations/marshmallow__shade/__init__.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    __version_info__ = tuple(LooseVersion(__version__).version)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR project-lib-versioned/python/test_project/src/tests/pipelines/data_science/test_data_science.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
===================== 5 tests collected, 1 error in 3.67s ======================

Traceback (most recent call last):
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
  File "/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/home/dataiku/.local/share/code-server/local-extensions/ms-python.python-2023.8.0-universal/out/client/extension.js:2:241129)
	at Object.onceWrapper (node:events:628:26)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1100:16)
	at Socket.<anonymous> (node:internal/child_process:458:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:301:12)]
